<Environment>
    <QtVersion>4.6.3</QtVersion>
    <QTestVersion>4.6.3</QTestVersion>
</Environment>
<TestFunction name="initTestCase">
<Incident type="pass" file="" line="0"/>
</TestFunction>
<TestFunction name="throwException">
<Incident type="fail" file="/local/user_builds/qt/4.6/src/testlib/qtestcase.cpp" line="1691">
    <Description><![CDATA[Caught unhandled exception]]></Description>
</Incident>
</TestFunction>
